version: "3"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: on-failure
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://host.docker.internal'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - 80:80
      - 22:22
    volumes:
      - ./data/logs:/var/log/gitlab
      - ./data/data:/var/opt/gitlab
      - ./data/config:/etc/gitlab
  runner:
    image: 'gitlab/gitlab-runner:latest'
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/runner-config:/etc/gitlab-runner