version: '3'

services:
  db:
    image: mongo:4.4
    command: ["--auth"]
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db