version: "3.7"

services:
  etcd:
    image: bitnami/etcd:3
    restart: on-failure
    ports:
      - 2379:2379
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - ./data:/bitnami/etcd