version: "3"

services:
  minio:
    image: minio/minio:latest
    restart: on-failure
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data