version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=123456
    ports:
        - 3306:3306
    volumes: 
        - ./data:/var/lib/mysql
