version: "3.7"

services:
  db:
    image: mysql:5.7
    # https://docs.docker.com/compose/compose-file/#restart
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
